name: rye
description: record your emotion.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
   sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  video_player: ^2.1.4 
  stacked_services: ^0.8.6
  get_it: ^7.1.3
  stacked: ^2.1.7
  cached_network_image: ^3.0.0
  firebase_core : ^1.2.0
  cloud_firestore: ^3.1.0
  camera: ^0.9.4+5
  camera_web: ^0.2.1+1
  path_provider: ^2.0.7
  path: ^1.8.0
  json_serializable: ^6.0.1
  json_annotation: ^4.4.0
  firebase_core_web: ^1.2.0
  line_icons: ^2.0.1
  shimmer: ^2.0.0
  share: ^2.0.4
  image_picker: ^0.8.4+4
  firebase_storage: ^10.1.0
  firebase_auth: ^3.2.0
  get: ^4.3.8
  video_thumbnail: ^0.4.3
  flutter_spinkit: ^5.1.0
  flutter_html: ^2.2.1
  flutter_webrtc: ^0.8.2
  uuid: ^3.0.5
  story_view: ^0.13.2
  grpc: ^3.0.2
  protobuf: ^2.0.1
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: assets/icon/logo.png
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


