name: rye
description: record your emotion.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
   sdk: flutter
  # icons
  cupertino_icons: ^1.0.4
  line_icons: ^2.0.1
  # media plugins    
  video_player: ^2.1.4 
  cached_network_image: ^3.0.0
  video_thumbnail: ^0.4.3
  # camera plugins
  camera: ^0.9.4+5
  camera_web: ^0.2.1+1
  # firebase plugins
  firebase_core : ^1.2.0
  firebase_core_web: ^1.2.0
  firebase_storage: ^10.1.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  # path helper
  path_provider: ^2.0.7
  path: ^1.8.0
  # code generator
  json_annotation: ^4.4.0
  # spinner
  flutter_spinkit: ^5.1.0
  # webrtc and html
  flutter_html: ^2.2.1
  flutter_webrtc: ^0.8.2
  # use hooks in flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.0
  freezed: ^1.1.1 # inmmutable and so on
  fpdart: ^0.0.14 # functional programming in flutter
    
dev_dependencies:
  # code generator
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: assets/icon/logo.png
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


